### ISSUE TITLE
index_not_found when using SEARCH_INDEX_PREFIX

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/invenio-communities#620]
Package version (if known): v2.8.0.dev20

## Describe the bug
When SEARCH_INDEX_PREFIX is defined, I am unable to create a new community. An index_not_found error is thrown when clicking 'Create Community' / by the POST to /api/communities.

## Steps to Reproduce
1. Create an instance with a SEARCH_INDEX_PREFIX
3. Note that normal index init creates the epected `SEARCH_INDEX_PREIFX`+communities... indexes in ES
4. Attempt to create a new instance (tested via UI)
5. In browser: POST to /api/communities returns 500 error
6. On instance STDOUT: index_not_found error thrown (by attempt to access non-prefixed index) - full output below

## Expected behavior

Should be possible to create a new community when SEARCH_INDEX_PREFIX is in use (and to extend this, all communities actions need to be tested/work with SEARCH_INDEX_PREFIXs)

## Screenshots (if applicable)

With `SEARCH_INDEX_PREFIX = 'kittler-lectures-'`

STDOUT of error:
```
[2022-05-09 14:25:15,857] WARNING in percolator: RequestError(400, 'mapper_parsing_exception', 'No field mapping can be found for the field with name [parent.communities.ids]')
[2022-05-09 14:25:15,977] WARNING in percolator: RequestError(400, 'mapper_parsing_exception', 'No field mapping can be found for the field with name [parent.communities.ids]')

### ^^^ likely a related problem? 

[2022-05-09 14:25:16,600] ERROR in app: Exception on /communities [POST]
Traceback (most recent call last):
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/invenio_records_resources/resources/records/resource.py", line 90, in create
    item = self.service.create(
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 327, in inner
    uow.commit()
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 284, in commit
    op.on_post_commit(self)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/invenio_records_resources/services/uow.py", line 197, in on_post_commit
    self._index.refresh(**self._kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch_dsl/index.py", line 360, in refresh
    return self._get_connection(using).indices.refresh(index=self._name, **kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 60, in refresh
    return self.transport.perform_request(
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    self._raise_error(response.status, raw_data)
  File "/srv/venv/kittler-lectures/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [communitymembers-members-member-v1.0.0]', communitymembers-members-member-v1.0.0, index_or_alias)
127.0.0.1 - - [09/May/2022 14:25:16] "POST /api/communities HTTP/1.1" 500 -
```

Note that invenio index init has created the correct (prefixed) indexes:

Output of http://localhost:9200/_cat/indices :

```
yellow open kittler-lectures-vocabularies-vocabulary-v1.0.0-1652103534                                 3B7-UtdyQKK3U1G4oJvZew 1 1 8396  0   4.2mb   4.2mb
yellow open kittler-lectures-affiliations-affiliation-v1.0.0-1652103534                                OQKKoWVVQb-oFxQtQiO_aA 1 1   15  0    74kb    74kb
yellow open kittler-lectures-communities-communities-v1.0.0-1652103534                                 tItzptIGRbu4wzTRQaqbRg 1 1    1  0   8.5kb   8.5kb
yellow open kittler-lectures-rdmrecords-records-record-v2.0.0-percolators                              1svGQMuQTA-yEv1LsP-2Pw 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-drafts-draft-v2.0.0-1652103534                                 53RaS8reTa-LRcCmZDOF7w 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-records-record-v3.0.0-1652103534                               pCMS3PY9RHy8BDgrl0ZQBg 1 1    0  0    226b    226b
yellow open kittler-lectures-funders-funder-v1.0.0-1652103534                                          UYTITqKDQomEz_Jg5D-tgg 1 1   21  0  42.8kb  42.8kb
yellow open kittler-lectures-rdmrecords-drafts-draft-v5.0.0-1652103534                                 VLpMkLC5S2eIm-hHNMGcaQ 1 1    0  0    226b    226b
yellow open kittler-lectures-users-user-v1.0.0-1652103534                                              KSP5_F49SASLLwjmy3JXLw 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-drafts-draft-v4.0.0-1652103534                                 TXm3dn4zQGWdot-oSiJMXQ 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-records-record-v4.0.0-1652103534                               XCSN3VyFSRavfSUU2iNnWA 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-drafts-draft-v3.0.0-1652103534                                 QB4qmXajRaGjCy4ovd3SNA 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-records-record-v5.0.0-1652103534                               OjykeLejTSy8ScGoM_pCZQ 1 1    0  0    226b    226b
yellow open kittler-lectures-communitymembers-archivedinvitations-archivedinvitation-v1.0.0-1652103534 0OoH3sx2SlGqWogt16fziA 1 1    0  0    226b    226b
yellow open kittler-lectures-subjects-subject-v1.0.0-1652103534                                        unWjrnomSC-ydFhISVgfEQ 1 1   40  0  52.8kb  52.8kb
yellow open kittler-lectures-rdmrecords-records-record-v4.0.0-percolators                              dpxaDlpwQ_eW7xkGKTHVdQ 1 1    2  0   8.5kb   8.5kb
yellow open kittler-lectures-communitymembers-members-member-v1.0.0-1652103534                         FHdgtop-SXWe0tbqdX6MRQ 1 1    1  0   9.5kb   9.5kb
yellow open kittler-lectures-requestevents-requestevent-v1.0.0-1652103534                              z1e_aBYoR-KXD2EYjJ1L7g 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-records-record-v3.0.0-percolators                              KvcPAoLkTD-66LgEKCb1DQ 1 1    0  0    226b    226b
yellow open kittler-lectures-groups-group-v1.0.0-1652103534                                            hfjdStTHS_qtYiNLcSkoFA 1 1    0  0    226b    226b
yellow open kittler-lectures-rdmrecords-records-record-v5.0.0-percolators                              Nd_qEMOnTSq_bU0ZsYIgsQ 1 1    2  0   8.5kb   8.5kb
yellow open kittler-lectures-awards-award-v1.0.0-1652103534                                            NyNyi2_RSBCp7_wW7q1oAw 1 1    0  0    226b    226b
yellow open kittler-lectures-requests-request-v1.0.0-1652103534                                        ICYjcx6vR3KVJkzBeLkqhg 1 1    0  0    226b    226b
yellow open kittler-lectures-names-name-v1.0.0-1652103534                                              tfoDj-SRTMO8EAHG36G8ZA 1 1 6585  0   7.2mb   7.2mb
yellow open kittler-lectures-rdmrecords-records-record-v2.0.0-1652103534                               OTViFyIwSd24bKyBuYzr7A 1 1    0  0    226b    226b
```

**Comment by ppanero** [comment]
As Dan mentioned, the indexes get created and it fails on members index refresh. The "bad" side of this is that the community has been created (along with the members) just the members index has not been refreshed.

Subsequent creation attempts will fail.

**Comment by ppanero** [comment]
The problem comes from the registration of the operation using the API.index field:
```python
uow.register(IndexRefreshOp(index=self.record_cls.index))
```

Whereas the actual expansion using the prefix happens in the indexer. Note that this problem happens in more places (many occurences already in the members service).

A possible solution would be to make the `IndexField` aware.
