### ISSUE TITLE
REST-API: communities/ invalid uuid will result to 500 Intternal server error

### ISSUE THREAD

**Issue by Samk13** [inveniosoftware/invenio-communities#735]
Package version: [version](https://github.com/inveniosoftware/invenio-communities/commit/2fd46cccec8df72e48f1421d78df291560566527)

## Describe the bug
when provide invalid UUID for the following routes:
- **GET {{baseURL}}/api/communities/{{com-id}}/members**
- **GET {{baseURL}}/api/communities/{{com-id}}/members/public**
- **GET {{baseURL}}/api/communities/{{com-id}}/invitations**
- **POST {{baseURL}}/api/communities/{{com-id}}/members**
- **POST {{baseURL}}/api/communities/{{com-id}}/invitations**
- **PUT {{baseURL}}/api/communities/{{com-id}}/members**
- **PUT {{baseURL}}/api/communities/{{com-id}}/invitations**
- **DELETE {{baseURL}}/api/communities/{{com-id}}/members**
you will get 500 internal server error

this issue is related to [347](https://github.com/inveniosoftware/invenio-records-resources/issues/347) and [46](https://github.com/inveniosoftware/invenio-users-resources/issues/46)

## Steps to Reproduce
1. Go to Postman
2. send req for each one of the routes mentioned above with invalid uuid
3. you get 500 res

## Expected behavior
quit gracefully with an error message

## Screenshots (if applicable)
```console
Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 65, in _coerce
    value = uuid.UUID(value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1116, in _init_compiled
    param = {
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1117, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1632, in process
    return impl_processor(process_param(value, dialect))
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 80, in process_bind_param
    value = self._coerce(value)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 68, in _coerce
    value = uuid.UUID(bytes=value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 186, in __init__
    raise ValueError('bytes is not a 16-char string')
ValueError: bytes is not a 16-char string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/home/samk13/dev/v9/invenio-communities/invenio_communities/members/resources/resource.py", line 46, in search
    hits = self.service.search(
  File "/home/samk13/dev/v9/invenio-communities/invenio_communities/members/services/service.py", line 329, in search
    return self._members_search(
  File "/home/samk13/dev/v9/invenio-communities/invenio_communities/members/services/service.py", line 405, in _members_search
    community = self.community_cls.get_record(community_id)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/invenio_records/api.py", line 384, in get_record
    obj = query.one()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2865, in one
    return self._iter().one()
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1725, in _execute_context
    self._handle_dbapi_exception(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1719, in _execute_context
    context = constructor(
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1116, in _init_compiled
    param = {
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1117, in <dictcomp>
    key: processors[key](compiled_params[key])
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 1632, in process
    return impl_processor(process_param(value, dialect))
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 80, in process_bind_param
    value = self._coerce(value)
  File "/home/samk13/.virtualenvs/my-site-master-venv/lib/python3.9/site-packages/sqlalchemy_utils/types/uuid.py", line 68, in _coerce
    value = uuid.UUID(bytes=value)
  File "/home/samk13/.pyenv/versions/3.9.12/lib/python3.9/uuid.py", line 186, in __init__
    raise ValueError('bytes is not a 16-char string')
sqlalchemy.exc.StatementError: (builtins.ValueError) bytes is not a 16-char string
[SQL: SELECT communities_metadata.created AS communities_metadata_created, communities_metadata.updated AS communities_metadata_updated, communities_metadata.id AS communities_metadata_id, communities_metadata.json AS communities_metadata_json, communities_metadata.version_id AS communities_metadata_version_id, communities_metadata.slug AS communities_metadata_slug, communities_metadata.bucket_id AS communities_metadata_bucket_id 
FROM communities_metadata 
WHERE communities_metadata.id = %(id_1)s AND (communities_metadata.json IS NULL) != true]
```

**Comment by Samk13** [comment]
[734](https://github.com/inveniosoftware/invenio-communities/pull/734)
