### ISSUE TITLE
Admin Page: Action Error Featuring Private Community

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-communities#920]
*from colleague*

Provide a more descriptive error when trying to feature a private community. I thought I was entering the start date wrong, until I checked the request logs. 

<img width="1624" alt="Screenshot 2023-03-10 at 4 27 34 PM" src="https://user-images.githubusercontent.com/8138663/224440253-afcbbf75-2f8d-4a99-8871-1aa474765fc7.png">

In the logs 
```
127.0.0.1 - - [10/Mar/2023 16:10:42] "POST /api/communities/ad4bc1f7-0f57-47ff-a0e6-e7d94d5f9cf3/featured HTTP/1.1" 400 -
[2023-03-10 16:10:44,241] DEBUG in errors: A resource error handler caught the following exception:
Traceback (most recent call last):
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/resources.py", line 65, in view
    return view_meth()
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/content_negotiation.py", line 116, in inner_content_negotiation
    return f(*args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 51, in inner
    return f(self, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/parsers/decorators.py", line 90, in inner
    return f(self, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/flask_resources/responses.py", line 39, in inner
    res = f(*args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/invenio_communities/communities/resources/resource.py", line 181, in featured_create
    item = self.service.featured_create(
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/invenio_records_resources/services/uow.py", line 324, in inner
    res = f(self, *args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/invenio_communities/communities/services/service.py", line 351, in featured_create
    self.run_components(
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/invenio_records_resources/services/base/service.py", line 72, in run_components
    getattr(component, action)(*args, **kwargs)
  File "/Users/me/.local/share/virtualenvs/digitalhub-2-jXqWR1nq/lib/python3.9/site-packages/invenio_communities/communities/services/components.py", line 115, in featured_create
    raise ValidationError(
marshmallow.exceptions.ValidationError: The community is not public.
```

**Comment by Samk13** [comment]
And for this issue, yes it's still there:

![Image](https://github.com/user-attachments/assets/107ea685-67f8-4f3e-9339-2aaeb9c46fb7)

**Comment by fenekku** [comment]
1.
> COMMUNITIES_ADMINISTRATION_DISABLED = False

Ok. Kind of strange thing to be able to disable 🤔 ...

2.

✅  That other issue still being there. Again my colleague will be looking into this this month.


3.

![Image](https://github.com/user-attachments/assets/1d7c964c-4627-450c-a27d-080284481a5c)

That "Request Membership" button should not show up at all. The full feature is not reviewed/finalized yet for v13. The default setting for it should set it false and if not I can make a PR to disable it for now.
